# Generated by Django 3.1.3 on 2020-12-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='positiveness',
            field=models.IntegerField(default=0),
        ),
    ]
