# Generated by Django 3.1.3 on 2020-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_positiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
